### ISSUE TITLE
About the StableDiffusionLatents2ImgPipeline

### ISSUE THREAD

**Issue by successhaha** [suduo94/D4M#1]
Hello,  Duo. This work is very interesting. 
I'm trying to follow it, but I've run into some issues.
When I run gen_syn_image_hjj.py, I found in the diffusers modules does not provide information about StableDiffusionLatents2ImgPipeline pipineline. 
I read the link (https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion/overview) can't find information about StableDiffusionLatents2ImgPipeline.
I hope you can provide the solution of this part.
Thank you very much.

**Comment by suduo94** [comment]
Thank you for your interest in this work! 
We have updated the [README.md](https://github.com/suduo94/D4M/blob/main/README.md) file for the repo and also uploaded the customized Latents2Img pipeline you need.
You may need to modify the source code of Diffusers Library to ensure that the customized pipeline can be imported smoothly. More detailed information can be found in the [README.md](https://github.com/suduo94/D4M/blob/main/README.md) file.
