### ISSUE TITLE
Regarding the  StableDiffusionGenLatentsPipeline

### ISSUE THREAD

**Issue by SunnyBhati** [suduo94/D4M#2]
Hi team,

Good work but I am coming across few issues while running the code.

I am trying to run the code for the( gen_prototype.py) script and upon running the script I get an error :

ImportError: cannot import name 'StableDiffusionGenLatentsPipeline' from 'diffusers'. Can you please explain and help me with the error?

**Comment by suduo94** [comment]
Thank you for your interest in our research! 
We have updated the [README.md](https://github.com/suduo94/D4M/blob/main/README.md) file for the repo. You can configure the right runtime environment by following the steps provided.  
Hope this guide will effectively help you resolve any 'ImportError' issues.

**Comment by zou-yawen** [comment]
> Hi team,
> 
> Good work but I am coming across few issues while running the code.
> 
> I am trying to run the code for the( gen_prototype.py) script and upon running the script I get an error :
> 
> ImportError: cannot import name 'StableDiffusionGenLatentsPipeline' from 'diffusers'. Can you please explain and help me with the error?

hi, do you solve this problem? I also meet this
