### ISSUE TITLE
Regarding the StableDiffusionGenLatentsPipeline

### ISSUE THREAD

**Issue by zou-yawen** [suduo94/D4M#4]
hi, I try to modify Diffusers source code according to scripts/README.md. However, it produces "ImportError: cannot import name 'StableDiffusionGenLatentsPipeline' from 'diffusers' " Could you please help me

**Comment by suduo94** [comment]
Hi there, thanks for your interest!
It would be best if you tried to modify the Diffusers source code according to the [Readme.md](https://github.com/suduo94/D4M/blob/main/scripts/README.md).
Remember to install the Diffusers package in an editable mode (See [this page](https://huggingface.co/docs/diffusers/main/en/installation#editable-install) for more details).

**Comment by zou-yawen** [comment]
> Hi there, thanks for your interest! It would be best if you tried to modify the Diffusers source code according to the [Readme.md](https://github.com/suduo94/D4M/blob/main/scripts/README.md). Remember to install the Diffusers package in an editable mode (See [this page](https://huggingface.co/docs/diffusers/main/en/installation#editable-install) for more details).

Thank you very much for your reply. I install the Diffusers package in an editable mode follow 
"git clone https://github.com/huggingface/diffusers.git
cd diffusers
pip install -e ".[torch]"
"
and  modify the Diffusers source code according to the [Readme.md] 
![image](https://github.com/user-attachments/assets/c1f9e3d5-6386-4968-a76d-6fa31eb5c5bb)
![image](https://github.com/user-attachments/assets/bbf578e8-e85e-4ee1-b85d-0c4e8a435fad)
![image](https://github.com/user-attachments/assets/824145a4-92f8-4165-9a1e-fc2740b03e85)
produce error  
![image](https://github.com/user-attachments/assets/eb16eb3e-3533-4bcd-8b3b-cf2a2f327525)
 Could you please help me, looking forward youre reply.

**Comment by suduo94** [comment]
I've checked your code and that's right. So I guess that this is because of the diffuser's version. We use the 0.21.0.dev0 in our paper, you could try again with this version.
