### ISSUE TITLE
hi，you said this work use diffusers v0210 in another issue ,however

### ISSUE THREAD

**Issue by Luo-Zhongwei** [suduo94/D4M#6]
PackagesNotFoundError: The following packages are not available from current channels:

  - diffusers=0.21.0*

**Comment by suduo94** [comment]
Hi, there.
Sorry for the late response.
You could just simply use "latents = pipe.vae.encode(images).latent_dist.sample()" to get the latent codes and futher do the prototype learning with these latents.
With the above suggestion, you could use any version of diffusers as you want without modifying its source code~
