### ISSUE TITLE
The accuracy of your teacher model

### ISSUE THREAD

**Issue by levunn** [suduo94/D4M#7]
Hello,

Thank you for your nice work!
I would like to know the models of the teacher networks used for each dataset (CIFAR-10, CIFAR-100, Tiny ImageNet, ImageNet1k) and their corresponding validation accuracies. This information would be very helpful for understanding the baseline performance.

Thank you!

**Comment by suduo94** [comment]
hi there, 
thx for your interesting! 
The teacher model used for cifar-10/100 is convnet-w128, just the same settings as the previous work mentioned in the related works (DM, MTT, Tesla etc.). 
Also, for imagenet-like datasets, their teacher models are resnet families (18-50-101). 
The Acc. is listed in our exps tables marked as “whole datasets”. 
You could find more details and supplementary materials in our arxiv’s paper.

**Comment by suduo94** [comment]
tips：whole dataset -> full dataset. 
Sorry for the mistake :P

**Comment by levunn** [comment]
Thank you, I got it!
